version: '3.9'
services:
  nats:
    image: nats:2.9.1-alpine
    ports:
      - 4222:4222
      - 8222:8222
  redis:
    image: redis:7.0.5-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:6.0.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Dzixxx
      - MONGO_INITDB_ROOT_PASSWORD=MongoPassword